services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      - DB_HOST=db
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./src/scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db: