services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      - DB_HOST=db
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: